dist: trusty
sudo: false
language: cpp

addons: 
        apt:
                sources:
                        - sourceline: "ppa:ubuntu-toolchain-r/test"
                packages:
                        - g++-5
script:
        - CXX=/usr/bin/g++ CC=/usr/bin/gcc cmake .
        - cmake --build . -- -j2


